name: game-theory
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.12.4
  - numpy=1.26.4
  - scipy=1.13.1
  - matplotlib=3.8.4
  - pandas=2.2.2
  - hydra-core=1.3.2
  - python-dotenv=0.21.0
  - omegaconf=2.3.0